### ISSUE TITLE
Sync Highlights in Articles

### ISSUE THREAD

**Issue by briansunter** [omnivore-app/logseq-omnivore#10] opened 2022-06-24 04:39 UTC
I noticed if you add new highlights to an article you already fetch it won't add the new highlights in the logseq plugin. Would be really nice to have the new highlights show up even after the article is fetched.

**Comment by wingy3181** [comment] 2022-06-24 06:36
@briansunter just FYI yea i found the same issue and raised a PR to partially resolve it to a certain extent

It will create a new block article for now at least

See #5 (in which this is really a duplicate of)

@sywhb is aware of this and i think is coming up with a better solution in general for it...

The PR for #5 just recently got merged so i hope it will get released soon.......

**Comment by sywhb** [comment] 2022-06-24 14:58
Refer to #3 and #5

**Closed** 2022-06-27 01:31 UTC
