### ISSUE TITLE
Failed to setup sync on logseq

### ISSUE THREAD

**Issue by jarodise** [omnivore-app/logseq-omnivore#3] opened 2022-06-21 14:27 UTC
I obtained the api auth key from the developer tool, then in the settings I input the log in info as 👍🏼 
{ 
    "username": "jarodise",
    "api key": "thelongstringkeyIgotfromdevelopertoo"
}

However, it didn't work. 

I kept on getting an error message as below: 

![CleanShot 2022-06-21 at 17 27 15@2x](https://user-images.githubusercontent.com/15899808/174824381-9dd95d1e-f7d6-437f-ae49-b529f944bf4b.png)

How should I set it properly so the sync would work? Thanks!

**Comment by pararang** [comment] 2022-06-21 21:56
I also experienced this issue on v0.7.3. and after upgrading to the latest (0.7.5), the issue was solved and replaced with this new one #4 :(

**Comment by wingy3181** [comment] 2022-06-22 09:48
I get the same issue as this and not the one you mentioned @pararang 

I did debug it and can see that this plugin is making a query via graphql POST to the omnivore graphql API

I noticed in the logseq developer tools that it is missing the auth request header
<img width="307" alt="image" src="https://user-images.githubusercontent.com/1212576/174998574-1a407e05-5ef2-4c45-845d-908fac6d810d.png">

also noticed that this plugin has a dependency to the logseq/libs at version 0.0.6 (
See https://github.com/omnivore-app/logseq-omnivore/blob/main/package.json#L26)

versus the 0.0.7 that i believe was released recently... (See https://github.com/logseq/logseq/blob/master/libs/package.json#L3)

Following the logic i can assume the issue is trying to get the settings from the logseq API on these few lines here
https://github.com/omnivore-app/logseq-omnivore/blob/main/index.ts#L262

Maybe if someone who has the development environment setup could try update the library to see if it fixes the issue

**Comment by wingy3181** [comment] 2022-06-22 11:37
Thanks @sywhb 
I think you released something recently and now its fixed?
I just uninstalled and reinstalled the plugin in logseq and can see a more friendlty settings UI
<img width="763" alt="image" src="https://user-images.githubusercontent.com/1212576/175019860-06031bf2-6bf8-4085-9069-ddf8a3ae91a2.png">

**Comment by sywhb** [comment] 2022-06-22 13:50
> I obtained the api auth key from the developer tool, then in the settings I input the log in info as 👍🏼 { "username": "jarodise", "api key": "thelongstringkeyIgotfromdevelopertoo" }
> 
> However, it didn't work.
> 
> I kept on getting an error message as below:
> 
> ![CleanShot 2022-06-21 at 17 27 15@2x](https://user-images.githubusercontent.com/15899808/174824381-9dd95d1e-f7d6-437f-ae49-b529f944bf4b.png)
> 
> How should I set it properly so the sync would work? Thanks!

Sorry for the inconvenience caused. I have released a new version (v1.4.0) to address this issue.

Could you please kindly update the plugin and try again?

**Comment by wingy3181** [comment] 2022-06-22 21:14
yep all good for me

**Comment by sywhb** [comment] 2022-06-24 14:56
Hey @wingy3181 , I have just released v1.4.3 to resolve this issue.

So now, the latest change of an article will be inserted in Omnivore page too and the old one will be removed.

Please let me know if it works for you!

**Comment by sywhb** [comment] 2022-06-24 14:59
Duplicate: #5 #10

**Comment by wingy3181** [comment] 2022-06-24 21:34
it works how i noticed the order of the highlights is in descending order of last creation
I think that's existing from my quick look at the code...
will have a look later

also i noticed the annotation could be added to the highlight and maybe a create nested block under the highlight for the annotation? is this something you want to do or you think will impact the performance

**Comment by sywhb** [comment] 2022-06-27 01:45
@wingy3181 Thank you for letting me know.

Yeah having the highlights in the order of the article would be more natural and useful. There is a location index in the response allows us to do it.

I don't think adding annotation as a nested block would impact the performance. It's just I haven't figured out a better way to present the highlights. We are planning to reformat the highlight section in this PR: https://github.com/omnivore-app/omnivore/issues/868

**Comment by sywhb** [comment] 2022-06-27 07:39
Duplicate here: https://github.com/sywhb/logseq-omnivore/issues/1

**Comment by sywhb** [comment] 2022-06-27 08:10
Also adding a deep link to the highlight here: https://github.com/omnivore-app/omnivore/issues/869

**Closed** 2022-06-29 05:16 UTC
